# -*- coding: utf-8 -*-
"""Assignment: Intelligent Document Q&A Assistant (Agentic RAG).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ea7_HiqoVFeIRYirp4-cOSeDFmB4qGR0
"""

!pip install pypdf chromadb sentence-transformers openai

from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
from openai import OpenAI
import chromadb
import uuid

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    #old nvdia key i used --->api_key="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" # Replace with your valid OpenRouter API key
    api_key="API_1"
)

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

from google.colab import files
uploaded = files.upload()

def load_pdf(file):

    reader = PdfReader(file)

    pages = []

    for i, page in enumerate(reader.pages):

        text = page.extract_text()

        pages.append({
            "page": i+1,
            "text": text
        })

    return pages

pages = load_pdf("AI_REPORT.pdf")

print("Pages loaded:", len(pages))

def chunk_text(pages, chunk_size=500, overlap=100):

    chunks = []

    for page in pages:

        text = page["text"]

        start = 0

        while start < len(text):

            chunk = text[start:start+chunk_size]

            chunks.append({
                "page": page["page"],
                "text": chunk
            })

            start += chunk_size - overlap

    return chunks

chunks = chunk_text(pages)

print("Total chunks:", len(chunks))

def create_embeddings(chunks):

    texts = [c["text"] for c in chunks]

    embeddings = embedding_model.encode(texts)

    return embeddings

embeddings = create_embeddings(chunks)

print("Embeddings created:", len(embeddings))

chroma_client = chromadb.Client()

try:
    chroma_client.delete_collection(name="document_store")
except:
    pass

collection = chroma_client.create_collection(name="document_store")

for i, chunk in enumerate(chunks):

    collection.add(

        ids=[str(uuid.uuid4())],

        documents=[chunk["text"]],

        embeddings=[embeddings[i].tolist()],

        metadatas=[{"page": chunk["page"]}]
    )

print("Chunks stored in ChromaDB")

def retrieve_chunks(query, k=3):

    query_embedding = embedding_model.encode([query]).tolist()

    results = collection.query(
        query_embeddings=query_embedding,
        n_results=k
    )

    return results

retrieve_chunks("What is artificial intelligence?")

def call_llm(prompt):

    response = client.chat.completions.create(

       #old nvidia model i used ----> model="nvidia/nemotron-nano-9b-v2:free",
        model="nvidia/nemotron-3-super-120b-a12b:free",

        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return response.choices[0].message.content

full_document = " ".join([p["text"] for p in pages])

def summarize_tool():

    prompt = f"""
    Summarize the following document:

    {full_document}
    """

    return call_llm(prompt)

print(summarize_tool())

def qa_tool(query):

    results = retrieve_chunks(query)

    context = "\n\n".join(results["documents"][0])

    pages = results["metadatas"][0]

    prompt = f"""
    Use the context below to answer the question.

    Context:
    {context}

    Question:
    {query}
    """

    answer = call_llm(prompt)

    citations = [f"Page {m['page']}" for m in pages]

    return answer, citations

answer, sources = qa_tool("What ethical concerns are mentioned in AI?")

print(answer)
print("Sources:", sources)

def agent_router(query):

    prompt = f"""
    Classify the query.

    If the user asks for summary or overview or brief return "summarize".

    Otherwise return "qa".

    Query: {query}
    """

    decision = call_llm(prompt)

    return decision.lower()

def ask(query):

    tool = agent_router(query)

    if "summarize" in tool:

        result = summarize_tool()

        print("Tool used: Summarize Tool\n")

        return result

    else:

        answer, sources = qa_tool(query)

        print("Tool used: Q&A Tool\n")

        return answer + "\n\nSources: " + ", ".join(sources)

while True:

    query = input("\nAsk something about the document (type 'exit' to stop): ")

    if query.lower() == "exit":
        print("Session ended.")
        break

    response = ask(query)

    print("\nAI Response:\n")
    print(response)

!pip install gradio
import gradio as gr

def classify_intent(query):

    prompt = f"""
    You are an intent classifier.

    If the user asks for a summary or overview  or brief of the document,
    respond with only the word:

    summarize

    If the user asks a specific question about the document,
    respond with only the word:

    qa

    User Query: {query}
    """

    decision = call_llm(prompt)

    return decision.strip().lower()

def ask_question(query):

    intent = agent_router(query)

    if "summarize" in intent:

        answer = summarize_tool()

        return f"Tool Used: Summarize Tool\n\n{answer}"

    else:

        answer, sources = qa_tool(query)

        return f"Tool Used: Q&A Tool\n\n{answer}\n\nSources: {', '.join(sources)}"

def process_pdf(file):
    try:
        global pages, chunks, embeddings, full_document, collection

        # Get file path from Gradio
        file_path = file.name if hasattr(file, "name") else file

        pages = load_pdf(file_path)

        chunks = chunk_text(pages)

        embeddings = create_embeddings(chunks)

        import chromadb
        chroma_client = chromadb.Client()

        collection = chroma_client.create_collection(name="document_store")

        for i, chunk in enumerate(chunks):

            collection.add(
                ids=[str(i)],
                documents=[chunk["text"]],
                embeddings=[embeddings[i].tolist()],
                metadatas=[{"page": chunk["page"]}]
            )

        full_document = " ".join([p["text"] for p in pages])

        return "✅ Document processed successfully!"

    except Exception as e:
        return f"❌ Error: {str(e)}"

"""IMPROVING UI

"""

import gradio as gr
import chromadb


def process_pdf(file):

    try:
        global pages, chunks, embeddings, full_document, collection

        # Get file path
        file_path = file.name if hasattr(file, "name") else file

        # Load PDF
        pages = load_pdf(file_path)

        # Chunk text
        chunks = chunk_text(pages)

        # Create embeddings
        embeddings = create_embeddings(chunks)

        # Initialize ChromaDB
        chroma_client = chromadb.Client()

        # Get or create collection
        collection = chroma_client.get_or_create_collection(name="document_store")

        # Clear previous embeddings
        try:
            collection.delete(where={})
        except:
            pass

        # Add embeddings
        for i, chunk in enumerate(chunks):

            collection.add(
                ids=[str(i)],
                documents=[chunk["text"]],
                embeddings=[embeddings[i].tolist()],
                metadatas=[{"page": chunk["page"]}]
            )

        # Store full document for summarization
        full_document = " ".join([p["text"] for p in pages])

        return "✅ Document processed successfully!"

    except Exception as e:
        return f"❌ Error: {str(e)}"


def ask_question(query):

    try:

        intent = classify_intent(query)

        if "summarize" in intent:

            answer = summarize_tool()

            return f"Tool Used: Summarize Tool\n\n{answer}"

        else:

            answer, sources = qa_tool(query)

            return f"Tool Used: Q&A Tool\n\n{answer}\n\nSources: {', '.join(sources)}"

    except Exception as e:

        return f"Error: {str(e)}"


with gr.Blocks() as demo:

    gr.Markdown("# 📄 AI Document Assistant")

    file = gr.File(label="Upload PDF", file_types=[".pdf"])

    process_btn = gr.Button("Process Document")

    status = gr.Textbox(
        label="Status",
        lines=3
    )

    process_btn.click(
        fn=process_pdf,
        inputs=file,
        outputs=status
    )

    query = gr.Textbox(
        label="Ask a question",
        lines=3,
        placeholder="Type your question here..."
    )

    answer = gr.Textbox(
        label="AI Response",
        lines=20,      # BIGGER RESPONSE AREA
        max_lines=40,  # Allows long responses
        show_copy_button=True
    )

    query.submit(
        fn=ask_question,
        inputs=query,
        outputs=answer
    )

demo.launch()

"""ADDING DWNLD OPTION"""

!pip install fpdf

from fpdf import FPDF
import gradio as gr
import chromadb


# ✅ PDF FUNCTION


def export_response_to_pdf(text):

    if not text or text.strip() == "":
        return None

    # ✅ CLEAN TEXT (important fix)
    clean_text = (
        text.replace("**", "")   # remove markdown bold
            .replace("’", "'")  # fix unicode quotes
            .replace("“", '"')
            .replace("”", '"')
    )

    # remove any unsupported characters
    clean_text = clean_text.encode("latin-1", "ignore").decode("latin-1")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    for line in clean_text.split("\n"):
        pdf.multi_cell(0, 8, line)

    file_path = "ai_response.pdf"
    pdf.output(file_path)

    return file_path


def process_pdf(file):

    try:
        global pages, chunks, embeddings, full_document, collection

        file_path = file.name if hasattr(file, "name") else file

        pages = load_pdf(file_path)
        chunks = chunk_text(pages)
        embeddings = create_embeddings(chunks)

        chroma_client = chromadb.Client()
        collection = chroma_client.get_or_create_collection(name="document_store")

        try:
            collection.delete(where={})
        except:
            pass

        for i, chunk in enumerate(chunks):
            collection.add(
                ids=[str(i)],
                documents=[chunk["text"]],
                embeddings=[embeddings[i].tolist()],
                metadatas=[{"page": chunk["page"]}]
            )

        full_document = " ".join([p["text"] for p in pages])

        return "✅ Document processed successfully!"

    except Exception as e:
        return f"❌ Error: {str(e)}"


# ✅ UPDATED FUNCTION (returns 2 outputs now)
def ask_question(query):

    try:
        intent = classify_intent(query)

        if "summarize" in intent:
            answer = summarize_tool()
            output = f"Tool Used: Summarize Tool\n\n{answer}"
        else:
            answer, sources = qa_tool(query)
            output = f"Tool Used: Q&A Tool\n\n{answer}\n\nSources: {', '.join(sources)}"

        return output, output   # 👈 IMPORTANT

    except Exception as e:
        return f"Error: {str(e)}", ""


with gr.Blocks() as demo:

    gr.Markdown("# 📄 AI Document Assistant")

    file = gr.File(label="Upload PDF", file_types=[".pdf"])
    process_btn = gr.Button("Process Document")

    status = gr.Textbox(label="Status", lines=3)

    process_btn.click(
        fn=process_pdf,
        inputs=file,
        outputs=status
    )

    query = gr.Textbox(
        label="Ask a question",
        lines=3,
        placeholder="Type your question here..."
    )

    answer = gr.Textbox(
        label="AI Response",
        lines=20,
        max_lines=40,
        show_copy_button=True
    )

    # ✅ STATE to store latest response
    response_state = gr.State("")

    # ✅ FILE output
    download_file = gr.File(label="Download Response")

    query.submit(
        fn=ask_question,
        inputs=query,
        outputs=[answer, response_state]   # 👈 store response
    )

    # ✅ DOWNLOAD BUTTON
    download_btn = gr.Button("📥 Download as PDF")

    download_btn.click(
        fn=export_response_to_pdf,
        inputs=response_state,   # 👈 uses stored text
        outputs=download_file
    )

demo.launch(share=True, debug=True)