# -*- coding: utf-8 -*-
"""Intelligent Multi-Source Research Assistant (Advanced RAG)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKhuqUsWYbIAXEYGyccTaXXJz8coUwxs
"""

!pip install langchain langchain-community langchain-openai
!pip install chromadb sentence-transformers
!pip install pypdf pandas markdown
!pip install rank_bm25

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    #old model model="nvidia/nemotron-nano-9b-v2:free",
    #NEW MODEL
    model="nvidia/nemotron-3-super-120b-a12b:free",
    # old api key api_key="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",
    openai_api_base="https://openrouter.ai/api/v1",
    temperature=0.2,
    #new api key
    api_key="API_1"
)

from langchain_community.document_loaders import PyPDFLoader

pdf_loader = PyPDFLoader("Fraud Detection.pdf")
pdf_docs = pdf_loader.load()

import pandas as pd

df = pd.read_csv("Fraud Detection - Sheet1.csv")

csv_docs = df.to_dict(orient="records")

from langchain_community.document_loaders import TextLoader

md_loader = TextLoader("Fraud Detection.md")
md_docs = md_loader.load()

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=100
)

pdf_chunks = splitter.split_documents(pdf_docs)
md_chunks = splitter.split_documents(md_docs)

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import Chroma

vectorstore = Chroma.from_documents(
    documents=pdf_chunks + md_chunks,
    embedding=embeddings,
    persist_directory="vectordb"
)

retriever = vectorstore.as_retriever(
    search_kwargs={"k":5}
)

def factual_qa(query):

    docs = vectorstore.similarity_search(query, k=5)

    context = "\n".join([d.page_content for d in docs])

    prompt = f"""
Answer the question using the context below.

Context:
{context}

Question:
{query}

Also cite the source filenames.
"""

    return llm.invoke(prompt)

def summarize_docs(topic):

    docs = vectorstore.similarity_search(topic, k=5)

    text = "\n".join([d.page_content for d in docs])

    prompt = f"""
Summarize the following information:

{text}

Provide a clear structured summary.
"""

    return llm.invoke(prompt)

def comparative_analysis(query):

    docs = vectorstore.similarity_search(query, k=5)

    context = "\n".join([d.page_content for d in docs])

    prompt = f"""
Analyze and compare information across the sources based on the following question.

Context:
{context}

Question:
{query}

Highlight relationships and differences. Specifically, look for and include any numerical performance metrics like accuracy, precision, and recall from the context. Present these numerical comparisons in a clear, structured way, ideally in a table format.
"""

    return llm.invoke(prompt)

def classify_query(query):

    prompt = f"""
Classify the user query into one category:

1. factual
2. comparative
3. summary

Query: {query}

Return only the category.
"""

    return llm.invoke(prompt).content.strip()

def agent(query):

    intent = classify_query(query)

    if "factual" in intent:
        return factual_qa(query)

    elif "comparative" in intent:
        return comparative_analysis(query)

    elif "summary" in intent:
        return summarize_docs(query)

    else:
        return factual_qa(query)

query = input("Enter your question: ")

response = agent(query)

print("\nAnswer:\n")
print(response)

from langchain_core.documents import Document
import pandas as pd

# Load CSV
csv_df = pd.read_csv("Fraud Detection - Sheet1.csv")
csv_records = csv_df.to_dict(orient="records")

csv_documents = []
for row in csv_records:
    content = (
        f"Transaction ID: {row['transaction_id']}, "
        f"Amount: {row['amount']}, "
        f"Merchant: {row['merchant']}, "
        f"User ID: {row['user_id']}, "
        f"Is Fraud: {row['is_fraud']}"
    )
    metadata = {"source": "transactions.csv", "transaction_id": row['transaction_id']}
    csv_documents.append(Document(page_content=content, metadata=metadata))

csv_chunks = splitter.split_documents(csv_documents)

vectorstore.add_documents(csv_chunks)

print("CSV data has been successfully added to the vector store.")

!pip install gradio
!pip install langchain langchain-community
!pip install chromadb sentence-transformers
!pip install pypdf

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gradio_app.py
# 
# import gradio as gr
# import os
# import pandas as pd
# from langchain_openai import ChatOpenAI
# from langchain_community.document_loaders import PyPDFLoader, TextLoader, CSVLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_community.vectorstores import Chroma
# from langchain_core.documents import Document
# 
# # Set the API key from environment variable
# # old api os.environ["OPENROUTER_API_KEY"] = "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"
# os.environ["OPENROUTER_API_KEY"] ="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"
# # --- LLM Initialization (Cached) ---
# def initialize_llm():
#     return ChatOpenAI(
#         #old model model="        nvidia/nemotron-3-super-120b-a12b:free",
# 
#         model="nvidia/nemotron-3-super-120b-a12b:free",
#         openai_api_key=os.getenv("OPENROUTER_API_KEY"),
#         openai_api_base="https://openrouter.ai/api/v1",
#         temperature=0.2
#     )
# 
# llm = initialize_llm()
# 
# # --- Agent Functions ---
# def factual_qa(query, vectorstore):
#     docs = vectorstore.similarity_search(query, k=5)
#     context = "\n".join([d.page_content for d in docs])
#     prompt_template = "Answer the question using the context below.\n\nContext:\n{context}\n\nQuestion:\n{query}\n\nAlso cite the source filenames."
#     prompt = prompt_template.format(context=context, query=query)
#     return llm.invoke(prompt).content
# 
# def summarize_docs(topic, vectorstore):
#     docs = vectorstore.similarity_search(topic, k=5)
#     text = "\n".join([d.page_content for d in docs])
#     prompt_template = "Summarize the following information:\n\n{text}\n\nProvide a clear structured summary."
#     prompt = prompt_template.format(text=text)
#     return llm.invoke(prompt).content
# 
# def comparative_analysis(query, vectorstore):
#     docs = vectorstore.similarity_search(query, k=5)
#     context = "\n".join([d.page_content for d in docs])
#     prompt_template = "Analyze and compare information across the sources based on the following question.\n\nContext:\n{context}\n\nQuestion:\n{query}\n\nHighlight relationships and differences. Specifically, look for and include any numerical performance metrics like accuracy, precision, and recall from the context. Present these numerical comparisons in a clear, structured way, ideally in a table format."
#     prompt = prompt_template.format(context=context, query=query)
#     return llm.invoke(prompt).content
# 
# def classify_query(query):
#     prompt_template = "Classify the user query into one category:\n\n1. factual\n2. comparative\n3. summary\n\nQuery: {query}\n\nReturn only the category."
#     prompt = prompt_template.format(query=query)
#     return llm.invoke(prompt).content.strip()
# 
# def agent(query, vectorstore):
#     intent = classify_query(query)
#     if "factual" in intent:
#         return factual_qa(query, vectorstore)
#     elif "comparative" in intent:
#         return comparative_analysis(query, vectorstore)
#     elif "summary" in intent:
#         return summarize_docs(query, vectorstore)
#     else:
#         return factual_qa(query, vectorstore)
# 
# # --- Gradio Interface Function ---
# def process_uploaded_files(files, user_query):
#     if not files:
#         return "Please upload at least one document."
# 
#     all_docs = []
#     for file in files:
#         try:
#             filepath = file.name
#             if filepath.endswith(".pdf"):
#                 loader = PyPDFLoader(filepath)
#             elif filepath.endswith(".md") or filepath.endswith(".txt"):
#                 loader = TextLoader(filepath)
#             elif filepath.endswith(".csv"):
#                 # For CSV, load into pandas first to convert to a consistent Document format
#                 df = pd.read_csv(filepath)
#                 csv_records = df.to_dict(orient="records")
#                 csv_documents = []
#                 for row in csv_records:
#                     content = ", ".join([f"{k}: {v}" for k, v in row.items()])
#                     metadata = {"source": os.path.basename(filepath)}
#                     csv_documents.append(Document(page_content=content, metadata=metadata))
#                 all_docs.extend(csv_documents)
#                 continue # Skip generic loader for CSV
#             else:
#                 return f"Unsupported file type: {os.path.basename(filepath)}"
#             all_docs.extend(loader.load())
#         except Exception as e:
#             return f"Error processing {os.path.basename(filepath)}: {e}"
# 
#     # Chunk documents
#     splitter = RecursiveCharacterTextSplitter(
#         chunk_size=800,
#         chunk_overlap=100
#     )
#     chunks = splitter.split_documents(all_docs)
# 
#     # Create embeddings and vector store
#     embeddings = HuggingFaceEmbeddings(
#         model_name="sentence-transformers/all-MiniLM-L6-v2"
#     )
#     vectorstore = Chroma.from_documents(chunks, embeddings)
# 
#     # Invoke the agent with the dynamically created vectorstore
#     try:
#         response = agent(user_query, vectorstore)
#         return response
#     except Exception as e:
#         return f"An error occurred during response generation: {e}"
# 
# # --- Gradio Interface ---
# iface = gr.Interface(
#     fn=process_uploaded_files,
#     inputs=[
#         gr.File(file_count="multiple", label="Upload PDF, CSV, or Markdown files"),
#         gr.Textbox(lines=3, placeholder="Enter your question here...", label="Question")
#     ],
#     outputs=gr.Textbox(lines=25, label="Answer", show_copy_button=True),
#     title="AI Knowledge Assistant (Gradio)",
#     description="Upload documents and ask questions based on their content."
# )
# if __name__ == "__main__":
#     iface.launch(share=True)
#

!python gradio_app.py

"""ADDING CONFIDENCE SCORE AND CITATIONS"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gradio_app.py
# 
# import gradio as gr
# import os
# import pandas as pd
# from langchain_openai import ChatOpenAI
# from langchain_community.document_loaders import PyPDFLoader, TextLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_community.vectorstores import Chroma
# from langchain_core.documents import Document
# 
# 
# os.environ["OPENROUTER_API_KEY"] = "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"
# 
# # --- LLM Initialization ---
# def initialize_llm():
#     return ChatOpenAI(
#         model="nvidia/nemotron-3-super-120b-a12b:free",
#         openai_api_key=os.getenv("OPENROUTER_API_KEY"),
#         openai_api_base="https://openrouter.ai/api/v1",
#         temperature=0.2
#     )
# 
# llm = initialize_llm()
# 
# # --- Confidence Function ---
# def get_confidence(docs):
#     if len(docs) >= 4:
#         return "High"
#     elif len(docs) >= 2:
#         return "Medium"
#     else:
#         return "Low"
# 
# # --- Helper: Build Context with Sources ---
# def build_context(docs):
#     return "\n\n".join([
#         f"Source: {d.metadata.get('source', 'unknown')} | Chunk: {i}\nContent: {d.page_content}"
#         for i, d in enumerate(docs)
#     ])
# 
# # --- Tools ---
# def factual_qa(query, vectorstore):
#     docs = vectorstore.similarity_search(query, k=5)
#     confidence = get_confidence(docs)
#     context = build_context(docs)
# 
#     prompt = f"""
#     Answer the question using ONLY the context below.
# 
#     Context:
#     {context}
# 
#     Question:
#     {query}
# 
#     At the end, list all source filenames used.
#     """
# 
#     answer = llm.invoke(prompt).content
#     return answer + f"\n\nConfidence: {confidence}"
# 
# def summarize_docs(query, vectorstore):
#     docs = vectorstore.similarity_search(query, k=5)
#     confidence = get_confidence(docs)
#     context = build_context(docs)
# 
#     prompt = f"""
#     Summarize the following content:
# 
#     {context}
# 
#     Provide a structured summary.
#     Also list source filenames.
#     """
# 
#     answer = llm.invoke(prompt).content
#     return answer + f"\n\nConfidence: {confidence}"
# 
# def comparative_analysis(query, vectorstore):
#     docs = vectorstore.similarity_search(query, k=5)
#     confidence = get_confidence(docs)
#     context = build_context(docs)
# 
#     prompt = f"""
#     Analyze and compare the information below.
# 
#     Context:
#     {context}
# 
#     Question:
#     {query}
# 
#     Include numerical comparisons (accuracy, precision, recall).
#     Present results clearly (table if possible).
#     Also list source filenames.
#     """
# 
#     answer = llm.invoke(prompt).content
#     return answer + f"\n\nConfidence: {confidence}"
# 
# # --- Intent Classification ---
# def classify_query(query):
#     prompt = f"""
#     Classify the query into one of:
#     - factual
#     - comparative
#     - summary
# 
#     Only return ONE word.
# 
#     Query: {query}
#     """
#     intent = llm.invoke(prompt).content.lower().strip()
# 
#     if "comparative" in intent:
#         return "comparative"
#     elif "summary" in intent:
#         return "summary"
#     else:
#         return "factual"
# 
# # --- Agent Dispatcher ---
# def agent(query, vectorstore):
#     intent = classify_query(query)
# 
#     if intent == "factual":
#         return "Tool Used: Factual Q&A\n\n" + factual_qa(query, vectorstore)
# 
#     elif intent == "comparative":
#         return "Tool Used: Comparative Analysis\n\n" + comparative_analysis(query, vectorstore)
# 
#     elif intent == "summary":
#         return "Tool Used: Summarization\n\n" + summarize_docs(query, vectorstore)
# 
#     else:
#         return "Tool Used: Factual Q&A\n\n" + factual_qa(query, vectorstore)
# 
# # --- Main Processing Function ---
# def process_uploaded_files(files, user_query):
#     if not files:
#         return "Please upload at least one document."
# 
#     all_docs = []
# 
#     for file in files:
#         try:
#             filepath = file.name
# 
#             if filepath.endswith(".pdf"):
#                 loader = PyPDFLoader(filepath)
#                 docs = loader.load()
# 
#             elif filepath.endswith(".md") or filepath.endswith(".txt"):
#                 loader = TextLoader(filepath)
#                 docs = loader.load()
# 
#             elif filepath.endswith(".csv"):
#                 df = pd.read_csv(filepath)
#                 docs = []
#                 for i, row in df.iterrows():
#                     content = ", ".join([f"{k}: {v}" for k, v in row.items()])
#                     docs.append(Document(
#                         page_content=content,
#                         metadata={"source": os.path.basename(filepath)}
#                     ))
#             else:
#                 return f"Unsupported file type: {os.path.basename(filepath)}"
# 
#             # Add source metadata if missing
#             for d in docs:
#                 if "source" not in d.metadata:
#                     d.metadata["source"] = os.path.basename(filepath)
# 
#             all_docs.extend(docs)
# 
#         except Exception as e:
#             return f"Error processing {os.path.basename(filepath)}: {e}"
# 
#     # --- Chunking ---
#     splitter = RecursiveCharacterTextSplitter(
#         chunk_size=800,
#         chunk_overlap=100
#     )
#     chunks = splitter.split_documents(all_docs)
# 
#     # --- Embeddings + Vector Store ---
#     embeddings = HuggingFaceEmbeddings(
#         model_name="sentence-transformers/all-MiniLM-L6-v2"
#     )
# 
#     vectorstore = Chroma.from_documents(chunks, embeddings)
# 
#     # --- Run Agent ---
#     try:
#         response = agent(user_query, vectorstore)
#         return response
#     except Exception as e:
#         return f"Error generating response: {e}"
# 
# # --- Gradio UI ---
# iface = gr.Interface(
#     fn=process_uploaded_files,
#     inputs=[
#         gr.File(file_count="multiple", label="Upload PDF, CSV, or Markdown files"),
#         gr.Textbox(lines=4, label="Enter your question")
#     ],
#     outputs=gr.Textbox(lines=25, label="AI Answer", show_copy_button=True),
#     title="AI Knowledge Assistant",
#     description="Upload documents and ask questions with source-based answers."
# )
# 
# if __name__ == "__main__":
#     iface.launch(share=True)

!python gradio_app.py

